project:
  type: website
  output-dir: docs

website:
  title: "Ml-project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Ml_notebook.qmd
        text: ProjectNotes
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



